import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Providers } from "./provider"
import FilterBar from "./components/filter"
import Header from "./components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="dark" lang="en">
      <body className="">
        <Header />
        <div className="flex w-[100%] min-h-[100vh]">
          <FilterBar />
          <div className="w-[85%]">
            <Providers>{children}</Providers>
          </div>
        </div>
      </body>
    </html>
  )
}
